[env]
WINEARCH = "win64"
WINEDEBUG = "-all"
WINEESYNC = "1"
WINEDLLOVERRIDES = "dxdiagn=d;winemenubuilder.exe=d"

DXVK_LOG_LEVEL = "warn"
DXVK_LOG_PATH = "none"

MESA_GL_VERSION_OVERRIDE = "4.4"
__GL_THREADED_OPTIMIZATIONS = "1"

[player]
renderer = "D3D11"
dxvk = true
dxvk_version = "2.2"
auto_kill_prefix = true

[player.env]
DXVK_HUD = "fps"

[player.fflags]
DFIntTaskSchedulerTargetFps = 640

[studio]
renderer = "D3D11"
dxvk_version = "2.2"
